### ISSUE TITLE
a typo in menu

### ISSUE THREAD

**Issue by wdoo01** [LegendRhine/WDTP#10]
![typo](https://cloud.githubusercontent.com/assets/11390318/25070792/402bc2b4-22da-11e7-8b1f-7236c279507f.png)

I believe it is "Open Recent".

**Comment by LegendRhine** [comment]
Modified. thanks.

**Comment by wdoo01** [comment]
Thank you. 
I believe your modification should work, but I can't confirm this because I can't compile this project recently (since efae0fa289d03169ab93b9f4afdf9afe4847b109 I think). Close this issue anyway.

**Comment by LegendRhine** [comment]
Yes, that dir has been removed from the source. 

I'm refactoring the whole editor recently, haven't been done yet. The lib-hacked code will be restored in the next few days and perhaps will be placed in another source dir.
