### ISSUE TITLE
希望的改进

### ISSUE THREAD

**Issue by iscraft** [LegendRhine/WDTP#11]
1.文件夹和文档能够加密码
2.logo.png小一些 高度在80像素内感觉会好看
3.创建时间和最后修改可以放在logo.png的后面靠页面右边的位置 这样打开文档就能看到时间
4.页面下面随机推荐高度调小一些 甚至可以去掉 或者在设置中可选 因为部分使用者创建创作收集整理文档 但不一定会发布为网站 就像上面说到的logo一样 应该尽可能的把重点留给这篇的正文 
5.前进的过程孤独艰辛 注意劳逸结合

**Comment by LegendRhine** [comment]
wow，这么多集中在一起了……

第一个：
之前，TODO List中有一条是项目加密（查看权限和编辑权限），两个密码，类似Office Word的这个功能。后来这个划去了。主要是：WDTP突出创作、公开与分享，不定位于私密类的记事和写作工具。私密类记事和记录方面，我写过一个中文名为“小隐本记”的软件，功能方面，二者有些地方互补，我不打算让它们撞车太多。如果加密，密码的读写有很多方案，比如写在项目文档中。但是项目文档几乎就是透明的，磁盘目录和md格式的文本文档，更是一目了然。WDTP的文档采用md文本格式，主要就是它的易读和其它任何文本编辑软件的直接可编辑。此外，这个软件目前依然开源，任何加密算法都不安全。即使闭源，如果不借助于更先进的外部硬件或远程机，也很难做到比较稳妥和彻底的“保密”。软件的加密（包括某些功能的权限限制与分配等）是双刃剑，给使用者带来的麻烦远多于便利。

对文本文档本身进行加密，这个目前没考虑过，不过修改（扩充）源码实现起来并不麻烦。加密算法的选用，有很多开源免费的方案，可酌情选用……：）

**Comment by LegendRhine** [comment]
第二个，项目logo可随意设置（系统菜单-修改当前主题-设置项目logo），页面显示的logo就是其原始的高度，宽度默认是165px。宽度可修改HtmlProcess类846行源码。

如果不打算显示logo，导航菜单之类的页面元素，直接修改模板文件，去掉相关的tags即可。系统菜单-修改当前主题-xxxx.html。WDTP的类、方法、数据成员、模板tags等等命名方式都是自解释的，一看便知。

**Comment by LegendRhine** [comment]
第三个，见2

**Comment by LegendRhine** [comment]
第四个，系统菜单-修改当前主题-全局样式表。html的渲染结果与所有html元素的样式、格式等控制，主要靠css，这个可以随便改。WDTP鼓励用户制作并分享个性化的主题（样式表和模板）。

**Comment by LegendRhine** [comment]
5. 谢谢！这个软件第一阶段的开发基本完成了。如无太大意外，除必要的bug修复和重要完善，我想暂时先这样（绘图功能，比如类似于思维导图之类做头脑风暴或另类归纳整理等，目前还没想好是否加到WDTP中。这个模块稍微弄一下就规模太大，都可以独立为一个新软件了）。另外一些“大”功能和新鲜的玩法，目前由于用户太少、软件开源等因素，可能不到实现的时机。也有可能把这个项目的部分或全部功能拉出去另起炉灶，目前还没想好：）无论如何，最近几个月太累了，把手头上关于这个项目的一些杂事处理一下之后，得休息一段时间缓缓劲：）

我很希望这个项目能有热心人接手，特别是年轻人。他们的想法多、点子多、干劲猛，肯定能玩出更多有趣的东西：）
