### ISSUE TITLE
可以添加发送到常用博客的功能吗，就像mweb一样

### ISSUE THREAD

**Issue by FeMiner** [LegendRhine/WDTP#12]

**Comment by LegendRhine** [comment]
Not quite sure exactly what you're asking, but WDTP is itself a blog and static site generator, isn't it?

**Comment by FeMiner** [comment]
因为自己搭建的服务增加了维护的成本，一旦需要迁移也比较困难，所以我倾向于将将自己的博客即上传到自己的服务器，也会上传到博客园、wordpress这样的平台，而这些平台是支持metaweblog api的，这样就可以离线编辑，直接发布了,目前Win系统中只有为知笔记具有类似的功能，但是是一个半成品，就这个半成品我忍受了三四年。你的这个产品我是从为知笔记的贴吧中看到的，如果同时能支持metaweblog api 离线发布，估计在技术人群中将很受欢迎，如果再加上一些常用网盘同步就完美了。我仅从我需求的博客功能提了这个建议，不过山湖路的功能不限于此。

**Comment by LegendRhine** [comment]
明白了：）很实用的想法和点子，不错！

我不太了解国内的博客平台、数据存储、云同步服务等方面的详情，如果他们提供了面向第三方开发者的API（兼容或考虑到C、C++），代码比较规范工整，算法实现比较先进高效，未来的维护更新相对比较稳定，给人足够的信心，并且授权协议和使用许可比较明晰公平，那么这个想法和需求就很有必要仔细考虑和认真琢磨一下，花一些时间研究并了解他们的API和有关约定之后，实现起来不会很麻烦：）这方面的详情和技术细节，欢迎进一步讨论并提供有关信息：）

我们也可以在WDTP这个“主线”的基础上分出一个开发支线，专门架构自己的、完全不同于目前所有同类产品的云服务，包括网页托管、数据同步、另类的互助群、推送、社交、数据分析、某些方面的统计、预测、归纳、下一代人类写作、文艺创作、作品发布与分享等方面在大数据、拓扑协作、机器学习与人工智能等方面的实验性探索等等。用户可以注册会员并取得一个唯一性的标识（比如山湖路XXX号，类似QQ号码或微信注册名这种，可用二级域名来访问或管理自己的数据、网页、后台设置中心等）。这方面，我已经做了一些准备工作，程序中已经做了这些方面的底层架构与初步实现，并且已经申请了两个顶级的域名：wdtp.pub和wdtp.me。前些天，WDTP拿到了第一笔投资，投资方就有这方面的建议。

能为更广泛的用户提供更多有益、高效、简洁而先进的服务与技术支持，让WDTP为他们创造更多的实际价值和真正有意义的便利，而无需付出经济、时间与精力等多方面的更多成本，是我个人下一步要转变当前的开发思维模式并需要深入思考的问题，也是需要长远谋划与稳妥实施的最繁重任务之一。现在还不好明确更多，但具体实现方面，我依然不想“人云亦云”，也在考虑新的模式。技术方面，我始终认为目前的云服务在数据托管与同步等方面，可以有更多惊人、有趣和罕见的玩法。实际上，将数据集中在一个对外“公开”的服务群上，对用户来说，并不安全方便，对开发方来说，维护管理太费时费力，还经常出力不讨好。这不应该是信息时代数据云服务的主流，也是WDTP目前为止没有在此方面发力的最根本原因。

关于建站和网页数据的迁移，WDTP应该是目前所有同类软件中最简单省事的（虽然我对更多同类型的“民用级、大众型”软件几乎一无所知）。WDTP的网页数据与域名无关，打包后上传解压，或者直接上传网站数据，不需要任何额外设置网站就可以运营。GitHub和国内的Coding.net等网站都提供免费的网页托管、Git控制与普通访客的正常浏览等功能，即使没有自己的顶级域名、不熟悉服务器维护管理技术也没关系。他们的服务和技术相对来说比较理想，也相当成熟和稳定。目前来说，是我个人最为推荐的建站和数据备份、同步方案。建站、发布和分享等方面，还可以本机开放端口和外部访问权限，使用一些动态解析并可以域名转向等方面的免费服务，或者局域网内部直接访问……这么做的话，上述步骤都无需，非常省心：）

**Comment by handeng** [comment]
如果能提供一个支持plugin的机制就OK
