### ISSUE TITLE
最新1.0.0626正式版出现无法最大化情况

### ISSUE THREAD

**Issue by the-sword** [LegendRhine/WDTP#14]
最新1.0.0626正式版出现无法最大化情况
![default](https://user-images.githubusercontent.com/15519458/28319684-2bd15aac-6c01-11e7-90f7-58878d993907.PNG)

**Comment by LegendRhine** [comment]
主窗口无法最大化，程序启动后默认全屏。这是WDTP特意做的设定，在0.9的某个版本中做的实现。目的是使用户更加专注，不易分心。

如果大家觉得这个设定不方便，可以再改回来：）

**Comment by the-sword** [comment]
多谢回复，我看版本更新已经修复了，给力。作为我来说，还是觉得有最大化会方便一些，因为平时会边看文档边做笔记，需要缩放、最小化、最大化场景切换。
