### ISSUE TITLE
win10在点击任何一个输入框的时候都会弹出虚拟键盘

### ISSUE THREAD

**Issue by Hazukiaoi** [LegendRhine/WDTP#15]
win10在点击任何一个输入框的时候都会弹出虚拟键盘
就算在PC版的环境下面也是一样，希望可以在PC模式下不会弹出虚拟键盘

**Comment by LegendRhine** [comment]
文本框聚焦或二次聚焦后，操作系统是否弹出虚拟键盘，WDTP不做假定，取决于操作系统在此方面的默认设置。
