### ISSUE TITLE
Okey, here we go :)

### ISSUE THREAD

**Issue by LegendRhine** [LegendRhine/WDTP#2]
Please let me know if you have any trouble with WDTP.
Any sensible suggestion will be appreciated, as well as crazy ideas :)

**Comment by visualwind** [comment]
建议
1. 支持直接粘贴图片。复制粘贴文章时，太多图片文件一个一个导入比较麻烦。
2. 能支持导出带图片的docx，或者没有与文章无关内容的“单纯”点的网页文件。
