### ISSUE TITLE
希望作者能去掉或者缩小生成页面里的软件信息

### ISSUE THREAD

**Issue by visualwind** [LegendRhine/WDTP#3]
希望作者能去掉或者缩小生存页面里的软件信息，图片。
这些信息可以弄到关于或者另外用个文档说明。
太占笔记信息位了

**Comment by LegendRhine** [comment]
生存页面？

是打算去掉默认生成的网页中的某些元素吗？直接修改模板文件，去掉不想显示的标签项（所有标签项均由双花括号包裹），而后重新生成整站即可。

**Comment by LegendRhine** [comment]
OK，已修改默认的样式表，减小页底版权信息的字体大小。
https://github.com/LegendRhine/WDTP/commit/b33bbb67e5c4586d298ba47e844cb0c3c3317478

所有用户也可以自行修改默认的样式表，页底版权部分的样式由id copyright控制。
如页面无需显示某些元素，也可参见上一条回复，修改模板文件，去掉不想显示的标签项。

**Comment by LegendRhine** [comment]
@visualwind 朋友，问题解决了没有？

如是，请及时关闭此issue. 谢谢
