### ISSUE TITLE
标题中超链接显示异常

### ISSUE THREAD

**Issue by wdoo01** [LegendRhine/WDTP#4]
问题代码：
```
### [sometext](https://github.com/LegendRhine/WDTP)
```

显示为

```
sometext">sometext
```

但
```
<h3>  [sometext](https://github.com/LegendRhine/WDTP) </h3>
```

就可以正常显示

**Comment by LegendRhine** [comment]
为什么要将文档中的标题作为文字型链接呢？能否告知具体的使用场景和意图？

WDTP中的一二三级标题，本身有锚点定位的作用，供[TOC]提取目录、锚链接及实现文档大纲等功能。锚点文本和大纲标记默认就是最后一个#号和空格之后、换行之前的完整内容。可以进行识别和转换并实现标题也可以同时作为文字链接等功能，但是有点繁琐，需要添加的代码以及要处理的特殊情况不少（比如标题文本中连续多个链接、多个断裂式的链接、文本中间某些内容成为链接，等等……这些也适合于其它一些标记套标记的情况）。

我觉得添加一大批代码来实现此类功能，有点“太沉重”，必要性不是太大。此外，标题本身的功能是概括或引领随后的行文，从文章结构的完整性、连贯性、行文逻辑和正常的阅读体验等方面来说，用标题作为中断当前阅读进程并跳转的标记，似乎都不太合适。

类似情况还有一些，写Markdown解析这个模块时，我做过一些考虑，最后没有采取面面俱到、所有情况都处理这种思路（大部分吧，有些特殊情况做了兼顾和实现）。

Markdown文本标记语言与html等超文本标记语言有所不同，它的初衷和目的是高效、易读与简单强调，不是内容呈现、精细处理、视觉及交互功能的丰富性。另外，使用Markdown等简单型文本标记语言有个原则，尽量不要标记套标记。

个人理解和看法，如有不妥，请批评指正。

**Comment by wdoo01** [comment]
只是个人的习惯用法

有时候会用 markdown 记下关于某篇文章的笔记或摘录，这些笔记不是成篇的文章。如果可能的话，我会将其中要点总结在标题中，但有时这些笔记是零碎的，不系统的，没有所谓的“完整性、连贯性、行文逻辑”, 比较难总结出一个标题, 反正这种笔记总要附上出处，于是干脆写在标题里。
```
### a note on [some article](url to the article)
```
或者一篇笔记有多个要点，各有三级标题，则用以下的一级标题
```
# notes on  [some article](url to the article)
```

由于以前用的笔记软件支持这样做， 所以没注意标记套标记的事情。

另外，其他“太沉重”的功能具体有哪些？至少是 [Markdown: Syntax](https://daringfireball.net/projects/markdown/syntax) 中提到的功能？ 我注意到 Reference-style links 好像不被支持（是这样么？）。这意味着“尚未实现此功能或开发中” 还是 “太沉重所以没必要”？ （或许应该新开一个 issue 来讨论?）

**Comment by LegendRhine** [comment]
WDTP对“传统的”Markdown做了简化和规范，某些方面又进行了扩展（这个标记语言本身没有强制统一标准），这一点在WDTP的文档中有说明。简化和扩展并没有严格的约束、参照和定义，也没有其他方面的考虑和设局（比如扩展用户群，为曲折的商业化进程做铺垫，或其他目的，等等）。大多数是根据我个人、几位朋友的实际需求和部分用户提出的要求，斟酌后实现的。

写Markdown解析这个模块，最初的设计原则是“效率第一，宁少勿多，够用即可”。另一个隐含的目的是：练手，特别是新鲜而另类的模式与功能。这个不限于解析这一个模块。随着扩展标记的增多（主要还是我个人人性中“贪婪”的因素占了主导，希望它能适应更广泛的需求，另类功能多多益善等等，这些有值得商榷和反思的一面。因为如果一个人同时兼任设计、架构与编码维护等职责，经常就会陷入细节的泥潭中），这个原则正在被打破。另一个因素是我没有料到用户的需求如此之多（这个软件设计和架构的时候，没有走大众型软件这个路子，原想就是我自己和几位朋友的小范围使用）。最近我也在考虑这个模块下一步的更新与维护，未来某个时候也有可能重构，使之更加开放和容易添加PR修补。这样，大部分有能力和条件的用户就可以很方便地满足个人所需。但是目前还没有过多考虑这一块。也就是，目前的做法还是：如果现有的不能满足用户的需求，他们提出来，或者提交PR，我斟酌并测试后，觉得可行，就及时加进去。如果涉及面太宽，需要动的代码太多，或者可能会影响稍后的某些功能实现，就会耐心解释后先放一放，暂时忽略或留到今后解决，比如重构某些功能时，看看有没有更好的思路和算法来实现。

Reference-style link等相对复杂的Markdown标记，我采用了另外的思路来解决。在WDTP中可通过“缩略语”实现。“缩略语”的功能更强大，适用的场景也更广泛。

关于“太沉重”的功能或者说尚未添加的此类功能，很难明确说是哪些哪些，代码在哪一行，如何设计和实现的，WDTP也很难给出一个细节方面的todo-list。因为这是一个个人业余时间的开源项目（虽然它目前几乎占据了我的所有时间），没有太严格的计划和目标方案。大方向就是个人所需、多合一功能、简洁高效、方便易用等等，可以少用或不用其它单打一、巨无霸的软件。有些功能或发展的大方向，如果用户提出来，我会仔细琢磨一下，就像上面说的，根据情况及时实现或暂时放一放。对“情况”的判断，目前只能是以我个人为主，下一步如果有热心同行参与进来，或者UnderwaySoft团队中其他人能腾出时间和人手，可能会大家集体讨论一下，而后决定。

大概就是这样吧。

**Comment by wdoo01** [comment]
那我就相信开发者的判断，暂时避免使用文档中未提及的功能。
不过作为提醒，留着这个 issue :)

**Comment by LegendRhine** [comment]
好的，谢谢。

看到这个issue后就做了备注和留存。今天一整天我也在考虑这些问题。文档中的标题，或许可以让它有更多新鲜的玩法和模式，承担多一些责任。但是现在一些想法还不清晰。如有好的思路，欢迎不吝指教。

**Comment by LegendRhine** [comment]
@wdoo01 此问题解决了，并不完美。但应该可以满足您目前的需求。

https://github.com/LegendRhine/WDTP/commit/63ea8157326d60131676453c169d06654044fe39
https://github.com/LegendRhine/WDTP/commit/3066677a5ac2195f2476a0edd510e09aa0d279a9
https://github.com/LegendRhine/WDTP/commit/a71caedb35c3f87b9e10fcb4b8d7c15835b3b029
https://github.com/LegendRhine/WDTP/commit/c3188242d7db6da22a809f86e4dbb5e2cc2308d1
https://github.com/LegendRhine/WDTP/commit/5c6e9f54a02cb97cc4159e91666dc971ae793ab6

**Comment by wdoo01** [comment]
测试了一下，看起来可以了，感谢。
