### ISSUE TITLE
批量修改提醒日期？

### ISSUE THREAD

**Issue by wdoo01** [LegendRhine/WDTP#5]
前几天我批量导入了一些文档，约100篇，现在都到期了。有没有方法批量修改或去掉提醒日期？

**Comment by LegendRhine** [comment]
Will take a look at this ASAP. Any suggestion about this would you like to share?

About 'WDTP remind':
http://underwaysoft.com/works/wdtp/faq.html#“复习/锤炼/提醒”三合一功能是怎么回事？

**Comment by LegendRhine** [comment]
Done it.
https://github.com/LegendRhine/WDTP/commit/edeeb0a793225c89a713b3cbcfc7c91758830823

Details:
http://underwaysoft.com/works/wdtp/updateList.html

**Comment by wdoo01** [comment]
It works. Thank you.
