### ISSUE TITLE
代码缩进显示不一致

### ISSUE THREAD

**Issue by owensys** [LegendRhine/WDTP#6]
带 tab 缩进的代码粘贴进来后，没有缩进了，但是网页中显示正常缩进。
比如：

```cpp
if (hFile == NULL)
{
    if (flag) { //都是 tab 缩进
        flag = !flag;
    }
    *result = -2;
    return false;
}
```

复制粘贴进去后会变成：
```cpp
if (hFile == NULL)
{
if (flag) {
flag = !flag;
}
*result = -2;
return false;
}
```
不便于编辑代码。
但是如果是空格缩进两边都是正常的。

**Comment by LegendRhine** [comment]
It would be better for me to reproduce this issue you encountered if there's a 'real' code snippet (or source file)...

**Comment by LegendRhine** [comment]
Confirm it. Thanks.

**Comment by LegendRhine** [comment]
Solved.

https://github.com/LegendRhine/WDTP/commit/7b5660f92bcec016c56fa7200c0789c31e2826bf

**Comment by LegendRhine** [comment]
Details:
http://underwaysoft.com/works/wdtp/updateList.html
