### ISSUE TITLE
URL链接中带括号时显示不正常

### ISSUE THREAD

**Issue by owensys** [LegendRhine/WDTP#7]
比如：
 ```
[Support For C++11 Features](https://msdn.microsoft.com/en-us/library/hh567368(v=vs.120).aspx)
```
在网页中会显示成：
```
Support For C++11 Features.aspx)
```

**Comment by LegendRhine** [comment]
Solved: https://github.com/LegendRhine/WDTP/commit/65dc2ab83013fc517ba32109a1726f18cb2728d3
not perfect though...

Details: http://underwaysoft.com/works/wdtp/updateList.html
