### ISSUE TITLE
Typing is blocked when completion/tips menu is triggered

### ISSUE THREAD

**Issue by wdoo01** [LegendRhine/WDTP#8]
In current version of WDTP, when a tip or completion is triggered, a menu will jump up and the user has to choose from one of the menu items or press ESC before he or she could type again. This feature is sometimes annoying  when there are English key words, because the tip mechanism is quite sensitive for English. 

For example, there is currently a key word `TWOE`(which is the abbreviation of the name of a book) in my `tips` file, and whenever I want to type words like `word` or `work`, I will be interrupted and have to press an ESC.

I could have chosen an abbreviation that contains no vowel letter nor common letter combination in this case, but I don't think I can find a proper one for every cases. Also I think it as a limitation because I have to take such things into consideration when I build my tips file.

**Comment by LegendRhine** [comment]
This is an order and I'm willing to mend it happily!

Such functions're just preliminary support for tips-bank of wdtp. I mean 'preliminary support' that with such a big feature, I expect there to be bugs although there are no known issues that I found while testing -- except few inconvenience you mentioned above. They need more time to be improved obviously... did you see the refactoring of this module the day before yesterday?

**Comment by wdoo01** [comment]
:(

**Comment by LegendRhine** [comment]
Never mind, just a kidding :)

I'm working on it! seems a little trouble occurred when input some damn ASCII characters while the tips-menu is showing...

**Comment by LegendRhine** [comment]
Done it!
https://github.com/LegendRhine/WDTP/commit/40f7f864022c32315296681334e48fbaa0cac4b7
https://github.com/LegendRhine/WDTP/commit/62e03945d7cc6076c6f7a22e0c8f2bff384366a0

**Comment by LegendRhine** [comment]
details: http://underwaysoft.com/works/wdtp/updateList.html

**Comment by wdoo01** [comment]
Tested. Thank you.
