### ISSUE TITLE
添加 linux 版本支持

### ISSUE THREAD

**Issue by yaoleifly** [LegendRhine/WDTP#9]
目前来看仅支持 mac 和 win ,希望可以添加 linux 支持，全平台 支持 以及云端服务应该是此类软件的开发方向。

**Comment by LegendRhine** [comment]
@yaoleifly 先生：谢谢建议。其它平台下的版本慢慢都会发布，这件事已经在备忘里了：）已有不少网友提出需要Linux和iOS等平台下的版本。我想先缓一缓，最主要的原因是：目前我一个人的时间和精力不够，同步维护三个平台下的版本有点吃力。WDTP还处在快速发展和完善阶段，我想先在macOS和Windows这两个桌面机用户量占绝对优势的平台下把架子搭起来，尽量搭完整些，搞扎实，等稍微稳定后再逐步向其它平台下移植。

Linux的发行版很多，有些方面不统一，变化较快，后期的维护管理会额外占用更多的时间。以Ubuntu为例，它下一步要换回Gnome，我觉得目前也需要观望一下：）
